тултип готов
js-tasks-ru/htmlcss-20220919_yuliya599 pull request #10
Opened 2022-10-18 17:13 UTC by Glyzina

2022-10-18 17:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-18 20:22 UTC, GSemikozov requested changes

2022-10-18 20:22 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
глобальные / вспомогательные стили , не относящиеся к компоненту, в файле стилей компонента нельзя описывать. Удалим

2022-10-22 16:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-22 16:07 UTC, Glyzina commented on 05-lection3/01-tooltip/tooltip.css
> +body {
В целом да, согласна, в конкретно этой задаче вынесла боди и описала в хэде. Понимаю что так не делаем, но лишь для этой задачи это требуется, иначе не видно всплывашку)

2022-10-23 17:53 UTC, GSemikozov approved these changes

2022-10-23 17:53 UTC, merged