Button dz
js-tasks-ru/htmlcss-20220919_yuliya599 pull request #3
Opened 2022-10-08 14:42 UTC by Glyzina

Макро-разметка главной страницы основного проекта и три кнопки с разных состояниях.

2022-10-08 14:53 UTC, GSemikozov requested changes

2022-10-08 14:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px; /*точно не фиксируем как на макете? */
ширину лучше жестко не фиксировать, она должна зависеть от вложенного контента

2022-10-08 14:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 16px 33px;
марджины в БЭМ на уровне блока не задаем. Вместо них здесь однозначно нужны паддинги как в макете

2022-10-08 14:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-style: normal;
не хватает font-family

2022-10-08 14:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:hover {
не только на ховер - можно сразу на уровне блока по умолчанию

2022-10-08 14:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
советую использовать pointer-events: none

2022-10-08 14:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--grey-3);}
вероятно box-sizing: border-box потребуется при добавлении бордера для этого типа кнопки?

2022-10-08 14:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;}
если транзишн общий у всех типов кнопок то унесем в класс блока

2022-10-10 08:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-10 08:35 UTC, GSemikozov approved these changes

2022-10-10 08:35 UTC, merged